services:
  medusa:
    build: .
    command: yarn start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '7001:9000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/medusa
      - REDIS_URL=redis://redis:6379
      - MEDUSA_ADMIN_EMAIL=admin@nabd.dhk
      - MEDUSA_ADMIN_PASSWORD=supersecret12345678
      - MEDUSA_ADMIN_FIRST=Admin
      - MEDUSA_ADMIN_LAST=User
      - MEDUSA_ADMIN_BACKEND_URL=http://localhost:7001
      - MEDUSA_BACKEND_URL=http://localhost:7001
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ../server-config/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - medusa
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
volumes:
  postgres-data:
