services:
  medusa:
    build: .
    command: yarn start
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - '7001:9000'
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ../server-config/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - medusa
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
volumes:
  postgres-data:
